[package]
name = "trivial_pixels_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "*"
pixel_loop = { version = "*", path = "../../", default-features = false, features = [
  "pixels",
] }
